a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
print ("The sum of the two numbers is: ", a+b)
print ("The difference of the two numbers is: ", a-b)
print ("The product of the two numbers is: ", a*b)  
print ("The quotient of the two numbers is: ", a/b)
print ("The remainder of the two numbers is: ", a%b)
print ("The floor division of the two numbers is: ", a//b)
print ("The exponentiation of the two numbers is: ", a**b)
